services:
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ecommerce-net


  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - SERVICE_NAME=user-service
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      user-db:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ecommerce-net
  
  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - SERVICE_NAME=product-service
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      product-db:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ecommerce-net


  user-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - ecommerce-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 10

  product-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5434:5432"
    networks:
      - ecommerce-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - "9200:9200"
    networks:
      - ecommerce-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - ecommerce-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - ecommerce-net


networks:
  ecommerce-net:
    driver: bridge
